### PR TITLE
Update dev_scripts.sql

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* Addresses database component of [v2: requests support for back end](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/256). 

#### Description

* Creates new requests table, labeled `requests_v2` (likely a temporary name), which will record information related to data requests.

#### Testing

* Interactions will need to be tested upon development of CRUD endpoints.

#### Performance

* Performance impact marginal.

#### Docs

* No docs created as of yet.

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
I'm a bit confused about this repo—if the point is to migrate regularly from `production` to `dev`, it seems odd that the schema and such would be defined here rather than in `data-sources-app`. Would this repo make sense as a directory in `data-sources-app`?

Sorry, I know you made this a week ago but I'm just now noticing.

**Comment by maxachis** [comment]
@josh-chamberlain An excellent question! 

1. I was imitating what was done with `data_sources_mirror`, which also performs regular database actions, and is maintained in its own separate repository. 
2. The functionality done by this is rather lightweight. Putting it in the `data_sources_app` repository would add more to an already quite sizeable repository, 
3. It would also mean that the droplet hosting this would be continually pulling a bunch of information not needed for the action (as one of the scripts in here, by design, pulls the latest version of the repository it's located in.
4. Putting something designed to set up a dev environment in a production repository gets things a little confusing. Right now we've got the main repository and a forked dev version. Which do we commit to? If it's the forked version, what happens when the fork is integrated into production? This keeps the logic cleaner.

I could probably come up with more post-hoc rationalizations if given enough time, but those are the ones I have right now.

**Comment by mbodeantor** [comment]
I don't have strong feelings on the repo, the droplet is already maintaining the full app repo for the mirror (although this will go away with the Airtable decomission). Doesn't seem too much like clutter since these are tables used by the API, but the schema definitions are not

**Comment by mbodeantor** [comment]
@maxachis 1. Currently all our column names for the rest of the tables are lower case
2. Looks like Car GPS is missing from the Police & public interactions section of the Gitbook taxonomy
3. @josh-chamberlain Might be a good time to review the request_status options to make sure they are all useful moving forward

**Comment by maxachis** [comment]
> @maxachis 1. Currently all our column names for the rest of the tables are lower case

@mbodeantor Acknowledged! Will address. In the future, may be able to automate with [sqlfluff](https://github.com/sqlfluff/sqlfluff), a sql linter.

**Comment by josh-chamberlain** [comment]
@mbodeantor I think all the status options are good

**Pull request merged**
